image: maven:3.6.3-openjdk-11-slim

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


stages:
  - compile
  - evaluation
  - deploy

Compile:
  stage: compile
  script:
    - mvn clean compile
  artifacts:
    paths:
      - alexaLambda/target/
      - uploadLambda/target/
      - helper/target/
    expire_in: 1 week
  
Test:
  stage: evaluation
  script:
    - mvn clean test package -e
  artifacts:
    paths:
      - alexaLambda/target/
      - uploadLambda/target/
    expire_in: 1 week

Style:
  stage: evaluation
  script:
    - mvn clean verify -Dmaven.test.failure.ignore=true -Dcheckstyle.failOnViolation=true -Dcheckstyle.violationSeverity=warning


Sonar:
  image: maven:3.6.3-jdk-11
  stage: evaluation
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - mvn verify sonar:sonar -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml,../target/site/jacoco-aggregate/jacoco.xml -Dsonar.qualitygate.wait=true
  allow_failure: true
  only:
    - master

Deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - master
  script:
    - aws sts get-caller-identity
    - aws lambda update-function-code --function-name Vergissmeinicht-Proto --publish --zip-file fileb://./alexaLambda/target/vmn-alexa-1.0-SNAPSHOT.jar
    - aws lambda update-function-code --function-name Vergissmeinicht-upload --publish --zip-file fileb://./uploadLambda/target/vmn-upload-1.0-SNAPSHOT.jar

