/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:078a1067-da59-4193-a966-f6f885572a2f",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_TpSyol5lu",
    "aws_user_pools_web_client_id": "54u7q64gjba6vvdk459f84j512",
    "oauth": {},
    "aws_user_files_s3_bucket": "vergissmeinnichtbucket145332-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
